title: LucasTVMS' Page
author: Lucas Vieira
email: lucas.tvms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips and newbie guides about Data Analysis.

# social links
twitter_username: lucas_tvms
github_username:  lucastvms

show_excerpts: true # set to false to remove excerpts on the homepage
